# coding: utf-8

## Starter独自設定
starter:

  ## 出力のターゲット。環境変数 $STARTER_TARGET で上書き可能。
  ## * pbook: 印刷用のモノクロPDFを出力。printing bookの略。
  ## * ebook: 電子用のカラーPDFを出力。electric bookの略。
  ## * tablet: タブレット用のカラーPDFを出力。
  target: ebook

  ## リンクのURLを脚注に埋め込む（PDFでのみ）。
  linkurl_footnote: false   # trueならリンクのURLを脚注に埋め込む（お勧め）
